packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@apollo/protobufjs': false
  '@clerk/shared': true
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
